sudo: false
language: python
python:
        - 2.7
        - 3.4
        - 3.5
install:
        - python setup.py install
        - pip install -r requirements-test.txt
        - pip install python-coveralls
script:
        - py.test tests --cov "$(./utils/rig_path.py)" --cov tests --durations=10
after_success:
        - coveralls
notifications:
        email: false
matrix:
    fast_finish: true
