import pytest

from spinner.scripts.wiring_stats import main

@pytest.mark.parametrize("num_boards", [3, 12, 24, 48, 120, 240, 1200])
def test_wiring_stats(num_boards, capsys):
	# Just a sanity check that the program doesn't crash. All outputs are
	# generated by functions tested fully elsewhere.
	assert main("-n {}".format(num_boards).split()) == 0
