import pytest

from spinner.scripts.wiring_stats import main

def test_wiring_stats(capsys):
	# Just a sanity check that the program doesn't crash. All outputs are
	# generated by functions tested fully elsewhere.
	assert main("-n 120".split()) == 0
